/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 turret.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    stand: THREE.Mesh
    turret: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/turret.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stand.geometry} material={nodes.stand.material} />
      <mesh geometry={nodes.turret.geometry} material={nodes.turret.material} position={[0, 2.3, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.3} />
    </group>
  )
}

useGLTF.preload('/turret.glb')
